DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id INT(11) NOT NULL AUTO_INCREMENT,
    email VARCHAR(200) DEFAULT NULL,
    username VARCHAR(45) DEFAULT NULL,
    hashed_password VARCHAR(200) DEFAULT NULL,
    first_name VARCHAR(45) DEFAULT NULL,
    last_name VARCHAR(45) DEFAULT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (id)
    
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS tasks;

CREATE TABLE tasks (
	id INT(11) NOT NULL AUTO_INCREMENT,
    task_name VARCHAR(200) DEFAULT NULL,
    category VARCHAR(200) DEFAULT NULL,
    date_taken DATE DEFAULT NULL,
    owner_id INT(11),
    PRIMARY KEY (id),
    FOREIGN KEY (owner_id) REFERENCES users(id)
    
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

